### ISSUE TITLE
Migration to System.Text.Json

### ISSUE THREAD

**Issue by josago97** [jtwotimes/PokeApiNet#44]
Hello, would it be possible to study the change to using System.Text.Json? I understand that using Newtonsoft is beneficial due to the issue of compatibility with previous versions. However, current (and some years-old obsolete) versions of .Net already were and are compatible with System.Text.Json. There are [benchmarks](https://www.kaels-kabbage.com/posts/newtonsoft-vs-system-text-json/) that show the improvement in efficiency of System.Text.Json compared to Newtonsoft.

**Comment by jtwotimes** [comment]
I have a release coming out soon that switches to `System.Text.Json` for all serialization, stay tuned.

**Comment by josago97** [comment]
Ohh, perfect, thank you.

**Comment by jtwotimes** [comment]
Just released v4.0.0 with change. Feel free to check it out.
